// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebOrder.Models;

#nullable disable

namespace WebOrder.Migrations.ErpDb
{
    [DbContext(typeof(ErpDbContext))]
    partial class ErpDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebOrder.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("WebOrder.Models.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ClientId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("WebOrder.Models.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.HasKey("LocationId");

                    b.HasIndex(new[] { "WarehouseId" }, "IX_Locations_WarehouseId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("WebOrder.Models.Manufacturer", b =>
                {
                    b.Property<int>("ManufacturerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ManufacturerId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("ManufacturerId");

                    b.ToTable("Manufacturers");
                });

            modelBuilder.Entity("WebOrder.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DelayedDates")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DiscountPercentage")
                        .HasColumnType("float");

                    b.Property<DateTime>("ExecutionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<DateTime>("RealExecutionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex(new[] { "ClientId" }, "IX_Orders_ClientId");

                    b.HasIndex(new[] { "SupplierId" }, "IX_Orders_SupplierId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("WebOrder.Models.OrderProduct", b =>
                {
                    b.Property<int>("OrderProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderProductId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderProductId");

                    b.HasIndex(new[] { "OrderId" }, "IX_OrderProducts_OrderId");

                    b.HasIndex(new[] { "ProductId" }, "IX_OrderProducts_ProductId");

                    b.ToTable("OrderProducts");
                });

            modelBuilder.Entity("WebOrder.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("EnergyClass")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("FabricType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<int?>("Size")
                        .HasColumnType("int");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<int?>("StorageTemperature")
                        .HasColumnType("int");

                    b.Property<int?>("WarrantyYears")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex(new[] { "CategoryId" }, "IX_Products_CategoryId");

                    b.HasIndex(new[] { "ManufacturerId" }, "IX_Products_ManufacturerId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("WebOrder.Models.ProductBlock", b =>
                {
                    b.Property<int>("ProductBlockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductBlockId"));

                    b.Property<double>("DiscountPercentage")
                        .HasColumnType("float");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("ProductBlockType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ProductBlockId");

                    b.HasIndex(new[] { "LocationId" }, "IX_ProductBlocks_LocationId");

                    b.HasIndex(new[] { "ProductId" }, "IX_ProductBlocks_ProductId");

                    b.ToTable("ProductBlocks");
                });

            modelBuilder.Entity("WebOrder.Models.ProductItem", b =>
                {
                    b.Property<int>("ProductItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductItemId"));

                    b.Property<int?>("ProductBlockId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ProductItemId");

                    b.HasIndex(new[] { "ProductBlockId" }, "IX_ProductItems_ProductBlockId");

                    b.ToTable("ProductItems");
                });

            modelBuilder.Entity("WebOrder.Models.ProductSupplier", b =>
                {
                    b.Property<int>("ProductSupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductSupplierId"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("ProductSupplierId");

                    b.HasIndex(new[] { "ProductId" }, "IX_ProductSupplier_ProductId");

                    b.HasIndex(new[] { "SupplierId" }, "IX_ProductSupplier_SupplierId");

                    b.ToTable("ProductSupplier", (string)null);
                });

            modelBuilder.Entity("WebOrder.Models.StockMovement", b =>
                {
                    b.Property<int>("StockMovementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StockMovementId"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DestinationLocationId")
                        .HasColumnType("int");

                    b.Property<int>("DestinationProductBlockId")
                        .HasColumnType("int");

                    b.Property<DateTime>("MovementDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MovementType")
                        .HasColumnType("int");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SourceLocationId")
                        .HasColumnType("int");

                    b.Property<int>("SourceProductBlockId")
                        .HasColumnType("int");

                    b.HasKey("StockMovementId");

                    b.HasIndex(new[] { "DestinationLocationId" }, "IX_StockMovements_DestinationLocationId");

                    b.HasIndex(new[] { "DestinationProductBlockId" }, "IX_StockMovements_DestinationProductBlockId");

                    b.HasIndex(new[] { "OrderId" }, "IX_StockMovements_OrderId");

                    b.HasIndex(new[] { "SourceLocationId" }, "IX_StockMovements_SourceLocationId");

                    b.HasIndex(new[] { "SourceProductBlockId" }, "IX_StockMovements_SourceProductBlockId");

                    b.ToTable("StockMovements");
                });

            modelBuilder.Entity("WebOrder.Models.StockMovementItem", b =>
                {
                    b.Property<int>("StockMovementItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StockMovementItemId"));

                    b.Property<int>("ProductItemId")
                        .HasColumnType("int");

                    b.Property<int>("StockMovementId")
                        .HasColumnType("int");

                    b.HasKey("StockMovementItemId");

                    b.HasIndex(new[] { "ProductItemId" }, "IX_StockMovementItems_ProductItemId");

                    b.HasIndex(new[] { "StockMovementId" }, "IX_StockMovementItems_StockMovementId");

                    b.ToTable("StockMovementItems");
                });

            modelBuilder.Entity("WebOrder.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("SupplierId");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("WebOrder.Models.ViewModels.ConfirmationviewModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExecutionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ConfirmationviewModel");
                });

            modelBuilder.Entity("WebOrder.Models.Warehouse", b =>
                {
                    b.Property<int>("WarehouseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WarehouseId"));

                    b.Property<string>("Location")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("WarehouseId");

                    b.ToTable("Warehouses");
                });

            modelBuilder.Entity("WebOrder.Models.Location", b =>
                {
                    b.HasOne("WebOrder.Models.Warehouse", "Warehouse")
                        .WithMany("Locations")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("WebOrder.Models.Order", b =>
                {
                    b.HasOne("WebOrder.Models.Client", "Client")
                        .WithMany("Orders")
                        .HasForeignKey("ClientId");

                    b.HasOne("WebOrder.Models.Supplier", "Supplier")
                        .WithMany("Orders")
                        .HasForeignKey("SupplierId");

                    b.Navigation("Client");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("WebOrder.Models.OrderProduct", b =>
                {
                    b.HasOne("WebOrder.Models.Order", "Order")
                        .WithMany("OrderProducts")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebOrder.Models.Product", "Product")
                        .WithMany("OrderProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WebOrder.Models.Product", b =>
                {
                    b.HasOne("WebOrder.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebOrder.Models.Manufacturer", "Manufacturer")
                        .WithMany("Products")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("WebOrder.Models.ProductBlock", b =>
                {
                    b.HasOne("WebOrder.Models.Location", "Location")
                        .WithMany("ProductBlocks")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebOrder.Models.Product", "Product")
                        .WithMany("ProductBlocks")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WebOrder.Models.ProductItem", b =>
                {
                    b.HasOne("WebOrder.Models.ProductBlock", "ProductBlock")
                        .WithMany("ProductItems")
                        .HasForeignKey("ProductBlockId");

                    b.Navigation("ProductBlock");
                });

            modelBuilder.Entity("WebOrder.Models.ProductSupplier", b =>
                {
                    b.HasOne("WebOrder.Models.Product", "Product")
                        .WithMany("ProductSuppliers")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebOrder.Models.Supplier", "Supplier")
                        .WithMany("ProductSuppliers")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("WebOrder.Models.StockMovement", b =>
                {
                    b.HasOne("WebOrder.Models.Location", "DestinationLocation")
                        .WithMany("StockMovementDestinationLocations")
                        .HasForeignKey("DestinationLocationId")
                        .IsRequired();

                    b.HasOne("WebOrder.Models.ProductBlock", "DestinationProductBlock")
                        .WithMany("StockMovementDestinationProductBlocks")
                        .HasForeignKey("DestinationProductBlockId")
                        .IsRequired();

                    b.HasOne("WebOrder.Models.Order", "Order")
                        .WithMany("StockMovements")
                        .HasForeignKey("OrderId");

                    b.HasOne("WebOrder.Models.Location", "SourceLocation")
                        .WithMany("StockMovementSourceLocations")
                        .HasForeignKey("SourceLocationId")
                        .IsRequired();

                    b.HasOne("WebOrder.Models.ProductBlock", "SourceProductBlock")
                        .WithMany("StockMovementSourceProductBlocks")
                        .HasForeignKey("SourceProductBlockId")
                        .IsRequired();

                    b.Navigation("DestinationLocation");

                    b.Navigation("DestinationProductBlock");

                    b.Navigation("Order");

                    b.Navigation("SourceLocation");

                    b.Navigation("SourceProductBlock");
                });

            modelBuilder.Entity("WebOrder.Models.StockMovementItem", b =>
                {
                    b.HasOne("WebOrder.Models.ProductItem", "ProductItem")
                        .WithMany("StockMovementItems")
                        .HasForeignKey("ProductItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebOrder.Models.StockMovement", "StockMovement")
                        .WithMany("StockMovementItems")
                        .HasForeignKey("StockMovementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductItem");

                    b.Navigation("StockMovement");
                });

            modelBuilder.Entity("WebOrder.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("WebOrder.Models.Client", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("WebOrder.Models.Location", b =>
                {
                    b.Navigation("ProductBlocks");

                    b.Navigation("StockMovementDestinationLocations");

                    b.Navigation("StockMovementSourceLocations");
                });

            modelBuilder.Entity("WebOrder.Models.Manufacturer", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("WebOrder.Models.Order", b =>
                {
                    b.Navigation("OrderProducts");

                    b.Navigation("StockMovements");
                });

            modelBuilder.Entity("WebOrder.Models.Product", b =>
                {
                    b.Navigation("OrderProducts");

                    b.Navigation("ProductBlocks");

                    b.Navigation("ProductSuppliers");
                });

            modelBuilder.Entity("WebOrder.Models.ProductBlock", b =>
                {
                    b.Navigation("ProductItems");

                    b.Navigation("StockMovementDestinationProductBlocks");

                    b.Navigation("StockMovementSourceProductBlocks");
                });

            modelBuilder.Entity("WebOrder.Models.ProductItem", b =>
                {
                    b.Navigation("StockMovementItems");
                });

            modelBuilder.Entity("WebOrder.Models.StockMovement", b =>
                {
                    b.Navigation("StockMovementItems");
                });

            modelBuilder.Entity("WebOrder.Models.Supplier", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("ProductSuppliers");
                });

            modelBuilder.Entity("WebOrder.Models.Warehouse", b =>
                {
                    b.Navigation("Locations");
                });
#pragma warning restore 612, 618
        }
    }
}
